### ISSUE TITLE
Module parse failed: /Users/Jason/Documents/workSpace/fe-new/node_modules/react-refresh-infinite-tableview/lib/ReactRefreshInfiniteTableView.js Unexpected token (19:6)

### ISSUE THREAD

**Issue by lzbSun** [calvinchankf/ReactRefreshinFiniteTableView#1]
```
Module parse failed: /Users/Jason/Documents/workSpace/fe-new/node_modules/react-refresh-infinite-   tableview/lib/ReactRefreshInfiniteTableView.js Unexpected token (19:6)
```

我这里webpack 打包的时候报错啊，有出现这个问题吗

**Comment by calvinchankf** [comment]
Hi @lzbSun ,
ReactRefreshInfiniteTableView.js的第19行是一個html tag `<div/>`，Unexpected token應該是因為它看不懂html tag，你webpack有用babel loader嗎？

**Comment by lzbSun** [comment]
有的。
   loaders: [{
      test: /.(js|jsx)$/,
      exclude: /node_modules/,
      loader: 'babel'
    }]

**Comment by calvinchankf** [comment]
奇怪，我還沒有試到你的情怳

不過，你有沒有試過在loader加presets?

```
module: {
    loaders: [{
      test: /\.js?$/,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        "presets": ["react", "es2015"]
      }
    },
    // other loaders...
    ]
}
```

記得還要npm install babel-preset-es2015  babel-preset-react
和加.babelrc

你可以看一看我的example怎樣setup
或
http://www.ruanyifeng.com/blog/2016/01/babel.html

**Comment by guoyang007** [comment]
@lzbSun 问题解决了么，我也是相同的报错。。。而且loaders和example中配置的一样，i need your help~

**Comment by lzbSun** [comment]
@guoyang007 后来没有解决，我自己写了一个RenderList

**Comment by geminiyellow** [comment]
@calvinchankf 你這個 List 已經是需要別人 override 才能用了，所以你直接返回 null 就好了。
改掉之後就沒有這個錯誤了。

**Comment by calvinchankf** [comment]
@geminiyellow 什麼意思？不太明白

**Comment by calvinchankf** [comment]
issue fixed
sorry to update late
it is because i didn't export the compiled version for others to use
